version: "2"

services:
  nginx:
    build: ./
    image: thanhson1085/nginx-autoreload
    volumes:
      - ./conf.d/default.conf:/etc/nginx/conf.d/default.conf
    ports:
      - "80:80"
      - "443:443"
